// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	big "math/big"

	mock "github.com/stretchr/testify/mock"
)

// RateServiceI is an autogenerated mock type for the RateServiceI type
type RateServiceI struct {
	mock.Mock
}

type RateServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *RateServiceI) EXPECT() *RateServiceI_Expecter {
	return &RateServiceI_Expecter{mock: &_m.Mock}
}

// FetchRatesUSD provides a mock function with no fields
func (_m *RateServiceI) FetchRatesUSD() (map[string]*big.Float, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FetchRatesUSD")
	}

	var r0 map[string]*big.Float
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]*big.Float, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]*big.Float); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*big.Float)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RateServiceI_FetchRatesUSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchRatesUSD'
type RateServiceI_FetchRatesUSD_Call struct {
	*mock.Call
}

// FetchRatesUSD is a helper method to define mock.On call
func (_e *RateServiceI_Expecter) FetchRatesUSD() *RateServiceI_FetchRatesUSD_Call {
	return &RateServiceI_FetchRatesUSD_Call{Call: _e.mock.On("FetchRatesUSD")}
}

func (_c *RateServiceI_FetchRatesUSD_Call) Run(run func()) *RateServiceI_FetchRatesUSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RateServiceI_FetchRatesUSD_Call) Return(_a0 map[string]*big.Float, _a1 error) *RateServiceI_FetchRatesUSD_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RateServiceI_FetchRatesUSD_Call) RunAndReturn(run func() (map[string]*big.Float, error)) *RateServiceI_FetchRatesUSD_Call {
	_c.Call.Return(run)
	return _c
}

// NewRateServiceI creates a new instance of RateServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateServiceI {
	mock := &RateServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
